name: first workflow

on: 
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: self-hosted
    steps:
    - name: firststep
      shell: cmd
      run: echo Hello World
   
 secondjob:
  runs-on: ubuntu-latest
  steps:
  - name: secondstep
    shell: bash
    run: | 
     echo this is the second job
     echo and this is multi pass
